### ISSUE TITLE
Question: $facet support in mongo4cats

### ISSUE THREAD

**Issue by adschwartz** [Kirill5k/mongo4cats#16]
Hi @Kirill5k , 

Thanks for all the hard work you put into this great project. 

I'm looking to build out a pagination feature so that it returns the total number of rows while I page over the results, using the same query (stage) to give me data as well as the full row count. I read about [$facet](https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/) in Mongodb that I'd like to use in mongo4cats, but I don't see any support for facet. Am I overlooking the support or is there a way I can achieve the same functionality using mongo4cats?

**Comment by Kirill5k** [comment]
Hey @adschwartz,

There is no support for `$facet` yet, but I can easily add it today.

The only caveat is that I won't be able to release it until next Thursday.

**Comment by Kirill5k** [comment]
This should now be available in v0.4.9

You can refer to [this unit test](https://github.com/Kirill5k/mongo4cats/blob/master/core/src/test/scala/mongo4cats/collection/MongoCollectionAggregateSpec.scala#L111) for a usage example

**Comment by adschwartz** [comment]
@Kirill5k This is awesome. I'll start applying this immediately. Looking forward to avoiding my double queries!
