### ISSUE TITLE
Mongo 3.6 required, but I don't have that

### ISSUE THREAD

**Issue by Miniontoby** [Kirill5k/mongo4cats#23]
Hi, I know this is not actually a bug.

But I get error `Server at localhost:27017 reports wire version 4, but this version of the driver requires at least 6 (MongoDB 3.6)`

Is there any version or any way to use the wire version 4? I can only install MongoDB 3.4

**Comment by Kirill5k** [comment]
Looking at the Mongodb Java driver [compatibility matrix](https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/#compatibility-table-legend), it looks like they did not test the latest version of the driver with MongoDB 3.4. That being said, Java driver v4.7 appears to be fine.

What version of mongo4cats are you using?
I think if you downgrade it to v6.4 or less it should be fine in your case.

**Comment by Miniontoby** [comment]
I changed the version to 0.6.4 and it works now!
