### ISSUE TITLE
Exception when using `$slice` in aggregations

### ISSUE THREAD

**Issue by lsissoko** [Kirill5k/mongo4cats#24]
Hi,

I'm getting an exception on `$slice` but I can't tell how I'm using it wrong:
```scala
Aggregate
  .project(Projection.excludeId)
  .unwind("$name", UnwindOptions().preserveNullAndEmptyArrays(false))
  .group("$_id", Accumulator.addToSet("uniqueNames", "$name"))
  .project(Projection.slice("uniqueNames", 1, 2))
```

> com.mongodb.MongoCommandException: Command failed with error 28724 (Location28724): 'Failed to optimize pipeline :: caused by :: First argument to $slice must be an array, but is of type: int' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Failed to optimize pipeline :: caused by :: First argument to $slice must be an array, but is of type: int", "code": 28724, "codeName": "Location28724"}

If I remove the `skip`argument and do `Projection.slice("uniqueNames", 2)`, I get:
> com.mongodb.MongoCommandException: Command failed with error 28667 (Location28667): 'Invalid $project :: caused by :: Expression $slice takes at least 2 arguments, and at most 3, but 1 were passed in.' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Invalid $project :: caused by :: Expression $slice takes at least 2 arguments, and at most 3, but 1 were passed in.", "code": 28667, "codeName": "Location28667"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)

From the errors, it looks like the `fieldName` is ignored in favor of the second argument.

This is my collection:
```js
[
  { _id: 1, age: 44, name: "A" },
  { _id: 2, age: 29, name: "B" },
  { _id: 3, age: 95, name: "B" },
  { _id: 4, age: 50, name: "C" },
  { _id: 5, age: 36, name: "D" },
  { _id: 6, age: 36, name: "B" },
]
```

This is the aggregation that I'm trying to build. I want to get the unique `name`s, skip the first one, and return the next two:
```ts
db.foo.aggregate(
  //  Expected after this stage:
  //      [ { _id: 0, names: [ 'A', 'B', 'B', 'C', 'B' ], total: 5 } ]
    {
      $group: {
        _id: 0,
        uniqueNames: { $push: {$toString: '$name'} },
      }
    },

  //  Expected after this stage:
  //      [ { uniqueNames: [ 'B', 'C' ] } ]
    {
      $project: {
        _id: 0,
        uniqueNames: {
          $slice: [{ $setIntersection: ['$uniqueNames'] }, 1, 2]
        }
      }
    },
)
```

If it helps, I'm using `mongo4cats-core:0.6.6` and also tried `0.6.4`, along with the latest MongoDB 6.0.4.

Have I stumbled upon a bug or am I doing something wrong?

**Comment by Kirill5k** [comment]
Hey, @lsissoko.

I suspect this might be a bug within MongoDB Java client, as I seem to be getting exactly same exception when creating aggregation pipeline with standard Java Bson syntax:

```scala
import com.mongodb.client.model.{Accumulators, Aggregates, Projections, UnwindOptions}

collection
  .aggregate[Document](
    List(
      Aggregates.project(Projections.excludeId()),
      Aggregates.unwind("$name", new UnwindOptions().preserveNullAndEmptyArrays(false)),
      Aggregates.group("$_id", Accumulators.addToSet("uniqueNames", "$name")),
      Aggregates.project(Projections.slice("uniqueNames", 1, 2))
    )
  ).all
```

On a different note, why wouldn't you just use `distinct` for achieving the same?
```scala
collection.distinct[String]("name").stream.drop(1).take(2).compile.toList
```

**Comment by Kirill5k** [comment]
It is awful, but as a quick fix to make it work you'll need to do something like this:
```scala
collection
  .aggregate[Document](
    List(
      Aggregates.project(Projections.excludeId()),
      Aggregates.unwind("$name", new UnwindOptions().preserveNullAndEmptyArrays(false)),
      Aggregates.group("$_id", Accumulators.addToSet("uniqueNames", "$name")),
      Aggregates.project(
        Projections.fields(
          new BsonDocument("uniqueNames", new BsonDocument("$slice", new BsonArray(asList(
            new BsonString("$uniqueNames"),
            new BsonInt32(2))
          )))
        )
      )
    )
  )
  .all
```

I'll try to fix it during this weekend.

**Comment by Kirill5k** [comment]
I've made a change to correct slice behaviour: [ef562110096200367c0c5387b61992a5d66675a3](https://github.com/Kirill5k/mongo4cats/commit/ef562110096200367c0c5387b61992a5d66675a3)

If you pull mongo4cats version 0.6.8, it should work now

**Comment by lsissoko** [comment]
> On a different note, why wouldn't you just use distinct for achieving the same?
>
> collection.distinct[String]("name").stream.drop(1).take(2).compile.toList

My real use case involves more work before beginning to look for unique values and I want to do as much as I can in the database before returning any data.

> If you pull mongo4cats version 0.6.8, it should work now

Version 0.6.8 works. Thanks!
