### ISSUE TITLE
Scala 3 & Circe: Can't upgrade since 0.6.8 due to circe

### ISSUE THREAD

**Issue by longliveenduro** [Kirill5k/mongo4cats#25]
I know this is a bug in circe, but this seems to block me from upgrading from 0.6.6:

https://github.com/circe/circe/issues/2089

On Scala 3.2.2 & ZIO 2 app start I get:

```
core timestamp=2023-03-08T09:01:56.263939006Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.lang.NoSuchMethodError: 'scala.collection.Iterable io.circe.DerivedEncoder.encodedIterable$(io.circe.DerivedEncoder, scala.Product)'
core 	at sttp.apispec.openapi.internal.InternalSttpOpenAPICirceEncoders$$anon$22.encodedIterable(InternalSttpOpenAPICirceEncoders.scala:28)

```

**Comment by Kirill5k** [comment]
Do you happen to know whether this issue has been fixed in circe 0.14.5?

If so, I can bump dependencies and do another release.

**Comment by longliveenduro** [comment]
Thanks @Kirill5k for the fast response!

According to https://github.com/circe/circe/releases, this seems to be fixed in 0.14.5, which was released a couple of days ago.

**Comment by Kirill5k** [comment]
I did a release. If you pull 0.6.9, everything should work.

**Comment by longliveenduro** [comment]
Thanks @Kirill5k , works like a charm!
