### ISSUE TITLE
ZIO Json integration

### ISSUE THREAD

**Issue by ioleo** [Kirill5k/mongo4cats#26]
It would be nice to see ZIO Json integration module added to the library.

**Comment by ioleo** [comment]
@Kirill5k I actually implemented it. Will open PR soon.

**Comment by Kirill5k** [comment]
Thanks. I was going to look into that tomorrow, but if you are happy to do it yourself - feel free to contribute.
It shouldn't be that big of deal. Just will need to replicate whatever is done in `circe` module.
