### ISSUE TITLE
Potential connection pool outage

### ISSUE THREAD

**Issue by alexgb1** [Kirill5k/mongo4cats#3]
This is more likely related to the underlying mongo-java-driver.
With the default settings, the connection pool will reach its max given a moderate amount of traffic and requests would start to timeout due to the connection pool being full. (It seems that the connection are not properly re-used, I'm following some issues/PRs in the mongo-java-driver and I can raise a PR once a new library is released)

**Comment by alexgb1** [comment]
I believe this is the issue that was been fixed recently https://github.com/mongodb/mongo-java-driver/pull/699 which is related the issue I ran into.

**Comment by Kirill5k** [comment]
That was fast, nice. Will update the driver once the newer version is out.
