### ISSUE TITLE
Document id forced to ObjectId

### ISSUE THREAD

**Issue by ingemaradahl** [Kirill5k/mongo4cats#32]
Hi!

It seems that mongo4cats imposes the limitation that stored document must have their `_id` field be of the `ObjectId` type: https://github.com/Kirill5k/mongo4cats/blob/2ddd402b23671be2d9b61136540953763c7b827a/modules/kernel/src/main/scala/mongo4cats/codecs/ContainerValueWriter.scala#L34.

Where I work, we're trying to incorporate more of the Typelevel ecosystem (cats, CE...), but we're explicitly _not_ using auto generated values for the `_id` field, or `ObjectId` instances in any way. What's the reasoning behind mongo4cats requiring the `ObjectId` type, or did it just end up being that way?

I could submit a PR to change this, but first I just want to raise the issue before doing the work, in case the limitation is intentional and the PR would never be accepted..

**Comment by Kirill5k** [comment]
Hey, @ingemaradahl 

Don't think there is any specific reasoning behind this decision.

Feel free to submit a PR for that change 👍

**Comment by Kirill5k** [comment]
@ingemaradahl 

I've updated `ContainerValueWriter` to be able to handle ids of different types: [a9f223c](https://github.com/Kirill5k/mongo4cats/commit/a9f223c1bf93a54fafc77e2a71db54fac8ce02a2)

Will release it later today

**Comment by ingemaradahl** [comment]
That was quick, thanks! I did an identical change, but I'm worried that https://github.com/Kirill5k/mongo4cats/blob/99b2c3699cab4cb1ff6d0ded5621f4e8c5626903/modules/kernel/src/main/scala/mongo4cats/codecs/DocumentCodecProvider.scala#L46 needs to change as well? I don't know how the underlying MongoDB driver calls this method, but I suspect that it shouldn't throw just because the document id isn't an `ObjectId`. The type signature indicates that the method should just convert the `mongo4cats.bson.BsonValue` to `org.bson.BsonValue`.

**Comment by Kirill5k** [comment]
Good spot! I totally forgot about that one.

I'll make an update 👍

**Comment by Kirill5k** [comment]
I've pushed a change: [35a832d](https://github.com/Kirill5k/mongo4cats/commit/35a832d13f812fcd2508236525a980cd99205167)

Should be available in `0.6.15`
