### ISSUE TITLE
Hard to close a session

### ISSUE THREAD

**Issue by axtsnee** [Kirill5k/mongo4cats#36]
It seems like `mongo4cats.client.ClientSession` implements the methods declared in `com.mongodb.reactivestreams.client.ClientSession` but not the ones from that interface's superinterface, `com.mongodb.session.ClientSession`. As far as I know, it is only possible to close a session by calling `close()` on `underlying`. I assume that is an oversight and not a deliberate design choice. Am I incorrect?

**Comment by Kirill5k** [comment]
I am ashamed to admit I never noticed that `ClientSession` has superinterface. I will provide implementations for the remaining methods in the next few days 👍

**Comment by Kirill5k** [comment]
I've updated method which creates session. From now on it will be returned wrapped in a `Resource`. This change is available in version `0.7.0`.

**Comment by axtsnee** [comment]
Thank you!
