### ISSUE TITLE
How do I set the cursor timeout?

### ISSUE THREAD

**Issue by satyagraha** [Kirill5k/mongo4cats#39]
As per: https://www.mongodb.com/docs/v7.0/reference/parameters/#mongodb-parameter-param.cursorTimeoutMillis

**Comment by Kirill5k** [comment]
Hello.

I believe this can be achieved by running a command on admin database:
```scala
        MongoClient
          .fromConnectionString[IO](s"mongodb://localhost:$mongoPort")
          .use { client =>
            for {
              db <- client.getDatabase("admin")
              _ <- db.runCommand(Document("setParameter" := 1, "cursorTimeoutMillis" := 300000L))
            } yield ()
          }
````

**Comment by satyagraha** [comment]
Thanks for the useful feedback. I was using `coll.find(...).boundedStream(1)` which in theory according to some MongoDB docs should cause the cursor to be kept active, but I think there may be lower-level buffering going on which caused the timeout due to apparent inactivity. FYI the application is very long-running as processing each record takes quite some time. This was the exception: https://www.mongodb.com/community/forums/t/mongocursornotfoundexception/14599 .

**Comment by Kirill5k** [comment]
After doing a quick google search, I've realised that I have not implemented `noCursorTimeout` method on `find` operation.

I'll release this change later today. Maybe this will solve your problem.

Will let you know when it is done.

**Comment by Kirill5k** [comment]
@satyagraha 

You update the library to `0.7.3`, then you should be able to use find with noCursorTimeout:
```
coll.find(...).noCursorTimeout(true).boundedStream(1)
```

Let me know if this helps
