### ISSUE TITLE
How to use `$addFields` aggregation

### ISSUE THREAD

**Issue by lenguyenthanh** [Kirill5k/mongo4cats#40]
First of all, thanks for your work on this library, We started to use it in [lichess.org](https://github.com/lichess-org/lila-seach) and it's just wonderful to use.

I just wonder how to use [`$addFields` aggregation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/addFields/) with mongo4cats. I see that We support some similar operation like `unwind`, `replaceWith` but not `addFields`.

I can create `Document`, `Bson` by my own, but I couldn't find a way to create an `Aggregate` our of them.

So, imho, We could solve this by two ways:
- support `$addFields` and some other missing aggregations out of the box
- support a way to construct aggration from `org.boson.Bson` or `BsonValue`.

I'm willing to create a PR if you think it's a good idea?

**Comment by Kirill5k** [comment]
@lenguyenthanh, I've just did a release with your change in it. You should now be able to use it in your code (v0.7.7) 👍

**Comment by lenguyenthanh** [comment]
thanks a lot @Kirill5k for your quick help ❤️, really appreciated.

We still some other missing aggregation operators. I'll continue work on those. Do prefer one pr per operator or one pr with all operators (with careful one commit per operator)?

**Comment by Kirill5k** [comment]
Either way is fine, whichever is easier for you.

If you give me names of these operator, I could help you out on this as well.

**Comment by lenguyenthanh** [comment]
I created a new issue with all the missing aggregation operators: https://github.com/Kirill5k/mongo4cats/issues/43
