### ISSUE TITLE
Distinct query breaks typed collections

### ISSUE THREAD

**Issue by tdbgamer** [Kirill5k/mongo4cats#6]
```scala
for {
  collection <- db.getCollection("name")
  res <- collection.distinct("column").first
} yield ()
```
This will fail if the column is not a `Document` which I'd expect it normally is not. So I ended up having to do this to make it work:
```scala
for {
  collection <- db.getCollection[String]("name", MongoDatabaseF.DefaultCodecRegistry)
  res <- collection.distinct("column").first
} yield ()
```
The issue with this is that now the type of the collection has to change to conform to the distinct query, so I can't do a `find` using the same collection. It seems like it might be a good idea to make aggregations pass a `Decoder` implicit for `distinct` that will decode the BsonValue into the required type.

**Comment by Kirill5k** [comment]
Turns out mongo's `distinct` supposed to return only values (and not the entire document as I mistakenly though) for a specified field across a single collection.

I've updated `distinct` implementation to allows specifying the type of the returned field. In addition to that I also added a method for adding more codecs to the collection's codec registry.

```scala
val result = for {
  coll   <- db.getCollectionWithCirceCodecs[Person]("people")
  _      <- coll.insertMany[IO](List(person("John", "Bloggs"), person("John", "Doe")))
  addresses <- coll.withAddedCirceCodecs[Address].distinct[Address]("address").all[IO]
} yield addresses
```

**Comment by tdbgamer** [comment]
sweet! Also I found an OOM bug that I can submit a PR for if you like. It may not be implemented the way you want, but can at least show you.

**Comment by tdbgamer** [comment]
Though it would be cool if `distinct` required the `Codec` so that you can't call distinct unless you have a deserializer for that type. If you forgot to call `withAddedCirceCodecs` it would fail at runtime.

**Comment by Kirill5k** [comment]
Yes, that would have been nice. Tbh, the only reason why I didn't do it the way you've described is because I couldn't come up with a neat name for that method (needs to be different from distinct).

I'll think about it and try to do something tonight 👍

**Comment by Kirill5k** [comment]
I followed your suggestion and added another method for doing distinct query with codecs:
```scala
for {
  coll <- db.getCollectionWithCodec[Person]("people")
  _    <- coll.insertMany[IO](List(person("John", "Bloggs"), person("John", "Doe")))
  distinctAddresses <- coll.distinctWithCodec[Address]("address").all[IO]
  _                 <- IO.println(distinctAddresses)
} yield ()
```
