### ISSUE TITLE
Dispatcher closing prematurely

### ISSUE THREAD

**Issue by rbakka** [Kirill5k/mongo4cats#8]
I think the `stream` call is closing `Dispatcher` resource prematurely. Subscribed callbacks can happen after the Dispatcher is closed if the Stream returned by `stream` is compiled. Here is the exception thrown when this happens:

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalStateException: dispatcher already shutdown
Caused by: java.lang.IllegalStateException: dispatcher already shutdown
	at cats.effect.std.Dispatcher$$anon$2.unsafeToFutureCancelable(Dispatcher.scala:283)
	at cats.effect.std.DispatcherPlatform.unsafeRunTimed(DispatcherPlatform.scala:60)
	at cats.effect.std.DispatcherPlatform.unsafeRunTimed$(DispatcherPlatform.scala:59)
	at cats.effect.std.Dispatcher$$anon$2.unsafeRunTimed(Dispatcher.scala:190)
	at cats.effect.std.DispatcherPlatform.unsafeRunSync(DispatcherPlatform.scala:52)
	at cats.effect.std.DispatcherPlatform.unsafeRunSync$(DispatcherPlatform.scala:51)
	at cats.effect.std.Dispatcher$$anon$2.unsafeRunSync(Dispatcher.scala:190)
	at mongo4cats.database.helpers$PublisherOps$$anon$4.onComplete(helpers.scala:77)
```

I think we can prevent this if we use fs2-reactive-streams. 

The `stream` implementation would change to:

```
    def stream[F[_]: Async]: Stream[F, T] =
      fromPublisher(publisher)
```

And I think with this approach the `boundedStream`s may not be required anymore.

**Comment by Kirill5k** [comment]
Hello. Thanks for sharing this!

I've used `fs2-reactive-streams` previously. It works, however the problem with that is that it is considerably slower than the regular Queue.

Could you provide an example of how I can recreate this error? I'll try to think of a workaround for that issue.

**Comment by rbakka** [comment]
> Hello. Thanks for sharing this!
> 
> I've used `fs2-reactive-streams` previously. It works, however the problem with that is that it is considerably slower than the regular Queue.
> 
> Could you provide an example of how I can recreate this error? I'll try to think of a workaround for that issue.

Thanks, I have seen this intermittently in a larger application with multiple parallel db calls made using one of CE3 par operations. I will try and see if I can create a small example to recreate this.

**Comment by rbakka** [comment]
I am not able to push a PR fo this repo but if we want to do it using regular Queue, this change in `mkStream` would eliminate that issue. Basically `publisher.subscribe` FFI should be wrapped in an effect as pointed out [here](https://fs2.io/#/guide?id=asynchronous-effects-callbacks-invoked-multiple-times) 
```
    private def mkStream[F[_]: Async](mkQueue: F[Queue[F, Option[Either[Throwable, T]]]]): Stream[F, T] =
      for {
        dispatcher <- Stream.resource(Dispatcher[F])
        queue      <- Stream.eval(mkQueue)
        _ <- Stream.eval {
          Sync[F].delay {
            publisher.subscribe(new Subscriber[T] {
              override def onNext(result: T): Unit =
                dispatcher.unsafeRunSync(queue.offer(Some(Right(result))))

              override def onError(e: Throwable): Unit =
                dispatcher.unsafeRunSync(queue.offer(Some(Left(e))))

              override def onComplete(): Unit =
                dispatcher.unsafeRunSync(queue.offer(None))

              override def onSubscribe(s: Subscription): Unit = s.request(Long.MaxValue)
            })
          }
        }
        stream <- Stream.fromQueueNoneTerminated(queue).evalMap(Async[F].fromEither)
      } yield stream
```

**Comment by rbakka** [comment]
The `safeGuard` change seems to have fixed this issue. You may want to wrap `publisher.subscribe` FFI in `Stream.eval(Sync[F].delay(...)).

**Comment by Kirill5k** [comment]
Good idea. Will do!
